routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::resource('Cliente','App\Http\Controllers\ClienteController');
Route::resource('distrito','App\Http\Controllers\distritoController');
//resource-> apunta a index,CREATE,UPDATE,EDIT,SHOW,DETROY

app/Models/Distrito.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Distrito extends Model
{
    protected $table = "distrito";
    public $timestamps = false; // OBVIA 2 CAMPOS CREATE_AT UPDATE_AT
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ClienteController extends Controller
{
    
    public function index()
    {   //SE UTILIZA PARA LISTAR REGISTROS
        
        return view('Cliente.listado');
    }


    public function create()
    {
        return view('Cliente.nuevo');
    }

    
    public function store(Request $request)
    {
        //
    }

    
    public function show($id)
    {
        //
    }

   
    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DistritoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Distrito;
use Session;
use Illuminate\Support\Facades\Redirect;
class DistritoController extends Controller
{
    
    public function index()
    {
        $registros=Distrito::get();
        //return $registros;
        return view("distrito.listado",compact('registros'));
    }

    
    public function create()
    {
        return view("distrito.nuevo");
    }

    
    public function store(Request $request)
    {
        $request->validate([
            'txt_nombre' => 'required',
            'txt_pais' => 'required',
            'txt_departamento' =>'required',
        ]);
        //return $request;
        $distrito=new Distrito;
        $distrito->dis_nombre=$request->txt_nombre;  
        $distrito->dis_pais=$request->txt_pais;
        $distrito->dis_departamento=$request->txt_departamento;
        $distrito->dis_fechacreacion=$request->txt_fundacion;
        $distrito->dis_cantidadpoblacion=$request->txt_poblacion;
        $distrito->dis_ubicacion=$request->txt_ubicacion;

       if($distrito->save()){
           Session::flash('exito','Registrado de manera Correcta');
           return Redirect::to('distrito');
       }
        else{
            Session::flash('error','Ocurrio un error,Verifique!');
            return Redirect::to('distrito/create');
        }


    }

   
    public function show($id)
    {
        $distrito=Distrito::findOrFail($id);
        return view('distrito.eliminar',compact('distrito'));
    }

    public function edit($id)
    {
        $distrito=Distrito::findOrFail($id);
        return view('distrito.editar',compact('distrito'));
    }

    
    public function update(Request $request, $id)
    {
        $distrito=Distrito::FindOrFail($id);
        $distrito->dis_nombre=$request->txt_nombre;  
        $distrito->dis_pais=$request->txt_pais;
        $distrito->dis_departamento=$request->txt_departamento;
        $distrito->dis_fechacreacion=$request->txt_fundacion;
        $distrito->dis_cantidadpoblacion=$request->txt_poblacion;
        $distrito->dis_ubicacion=$request->txt_ubicacion;

       if($distrito->save()){
           Session::flash('exito','Editado de manera Correcta');
           return Redirect::to('distrito');
       }
        else{
            Session::flash('error','Ocurrio un error,Verifique!');
            return Redirect::to('distrito/'.$id.'/edit');
        }
    }

    
    public function destroy($id)
    {
        try{
            //FLUJO SIN EXCEPCIONES
            Distrito::destroy($id);
            Session::flash('exito','Eliminado de manera Correcta');
            return Redirect::to('distrito');
        }catch(\Illuminate\Database\QueryException $e){
            //EN CASO DE UNA EXCEPCION
            Session::flash('error', $e);
            return Redirect::to('distrito');

        }
        

    }
}

resources/views/Distrito/editar.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Distrito</title>
    @include('layout.script_cabecera')
</head>
<body>
    <div class="container">
        <h3>Editar Distrito</h3>
        <div class="row">
            @if(Session('exito'))
            <div class="Aler alert-success">
                {{session('exito')}}
            </div>
            @endif
            @if(Session('error'))
            <div class="Aler alert-danger">
                {{session('error')}}
            </div>
            @endif
        </div>
        <hr>
        <form action="{{route('distrito.update',$distrito->id)}}" method="POST">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="exampleInputEmail1">Nombre</label>
                <input type="text" class="form-control" id="txt_nombre" name="txt_nombre" required value="{{$distrito->dis_nombre}}">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">País</label>
                <input type="text" class="form-control" id="txt_pais" name="txt_pais" required  value="{{$distrito->dis_pais}}">
            </div>
            </div>
            <div class="container form-group">
                <label for="exampleInputEmail1">Despartamento</label>
                <input type="text" class="form-control" id="txt_departamento" name="txt_departamento" required  value="{{$distrito->dis_departamento}}">
            </div>>
            </div>
            <div class="container form-group">
                <label for="exampleInputEmail1">Fecha de Fundacion</label>
                <input type="date" class="form-control" id="txt_fundacion" name="txt_fundacion" require  value="{{$distrito->dis_fechacreacion}}">
            </div>>
            </div>
            <div class="container form-group">
                <label for="exampleInputEmail1">Población</label>
                <input type="text" class="form-control" id="txt_poblacion" name="txt_poblacion" required  value="{{$distrito->dis_cantidadpoblacion}}">
            </div>>
            </div>
            <div class="container form-group">
                <label for="exampleInputEmail1">Ubicacion</label>
                <input type="text" class="form-control" id="txt_ubicacion" name="txt_ubicacion" required  value="{{$distrito->dis_ubicacion}}">
            </div>>
            </div>
            <button type="submit" class="btn btn-primary">Editar</button>
            <a href="{{url('distrito')}}" class="btn btn-primary">Volver</a>
        </form>  
    </div>
    @include('layout.script_pie')
</body>
</html>

resources/views/Distrito/eliminar.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Distrito</title>
    @include('layout.script_cabecera')
</head>
<body>
    <div class="container">
        <h3>Eliminar Distrito</h3>
        <div class="row">
            @if(Session('exito'))
            <div class="Aler alert-success">
                {{session('exito')}}
            </div>
            @endif
            @if(Session('error'))
            <div class="Aler alert-danger">
                {{session('error')}}
            </div>
            @endif
        </div>
        <hr>
        <form action="{{route('distrito.destroy',$distrito->id)}}" method="POST">
            @method('DELETE')
            @csrf
            <center>
                <h3>Atencion,Estas a punto de eliminar el siguiente registro:</h3>
                <h4><b>{{$distrito->dis_nombre}} {{$distrito->dis_pais}}</b></h4>
                <hr>
                <button type="submit" class="btn btn-danger btn-sm">Confirmar</button>
                <a href="{{url('distrito')}}" class="btn btn-primary btn-sm">atras</a>
            </center>
        </form>  
    </div>
    @include('layout.script_pie')
</body>
</html>

resources/views/Distrito/listado.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listado de Distritos</title>
    @include('layout.script_cabecera')
</head>
<body>
    <div class="container-fluid">
        <h3>Lista de Distritos:</h3>
        <a class ="btn btn-success btn-sm"href="{{url('distrito/create')}}">Agregar nuevo Distrito</a>
        <div class="">
            <br>
            @if(Session('exito'))
            <div class="Aler alert-success">
                {{session('exito')}}
            </div>
            @endif
            @if(Session('error'))
            <div class="Aler alert-danger">
                {{session('error')}}
            </div>
            @endif
        </div>
        <hr>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">País</th>
                    <th scope="col">Departamento</th>
                    <th scope="col">Fecha de Fundacion</th>
                    <th scope="col">Población</th>
                    <th scope="col">Ubicación</th>
                    <th scope="col">Acciones</th> 
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($registros as $registros)
                <tr>
                    <th scope="row">{{$registros->dis_nombre}}</th>
                    <td>{{$registros->dis_pais}}</td>
                    <td>{{$registros->dis_departamento}}</td>
                    <td>{{$registros->dis_fechacreacion}}</td>
                    <td>{{$registros->dis_cantidadpoblacion}}</td>
                    <td>{{$registros->dis_ubicacion}}</td>
                    <td>
                        <a href="{{route('distrito.edit',$registros->id)}}" class="btn btn-sm btn-info">Editar <i class="fas fa-pencil-alt"></i></a>
                        <a href="{{route('distrito.show',$registros->id)}}" class="btn btn-sm btn-danger">Eliminar <i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @include('layout.script_pie')
</body>
</html>

resources/views/Distrito/nuevo.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nuevo Distrito</title>
    @include('layout.script_cabecera')
</head>
<body>
    <div class="container">
        <h3>Nuevo Distrito</h3>
        <div class="row">
            @if(Session('exito'))
            <div class="Aler alert-success">
                {{session('exito')}}
            </div>
            @endif
            @if(Session('error'))
            <div class="Aler alert-danger">
                {{session('error')}}
            </div>
            @endif
        </div>
        <hr>
        <form action="{{url('distrito')}}" method="POST">
            @csrf
            <div class="form-group">
                <label for="exampleInputEmail1">Nombre (*)</label>
                <input type="text" class="form-control" id="txt_nombre" name="txt_nombre" value="{{old('txt_nombre')}}">
                @error('txt_nombre')
                    <span class="error" role="alert" style="color:red">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">País (*)</label>
                <input type="text" class="form-control" id="txt_pais" name="txt_pais" value="{{old('txt_pais')}}">
            </div>
            @error('txt_pais')
                    <span class="error" role="alert" style="color:red">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            <div class="form-group">
                <label for="exampleInputEmail1">Despartamento (*)</label>
                <input type="text" class="form-control" id="txt_departamento" name="txt_departamento" value="{{old('txt_departamento')}}">
            </div>
            @error('txt_departamento')
                    <span class="error" role="alert" style="color:red">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            <div class="form-group">
                <label for="exampleInputEmail1">Fecha de Fundacion</label>
                <input type="date" class="form-control" id="txt_fundacion" name="txt_fundacion" value="{{old('txt_fundacion')}}">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Población</label>
                <input type="text" class="form-control" id="txt_poblacion" name="txt_poblacion" value="{{old('txt_poblacion')}}">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Ubicacion</label>
                <input type="text" class="form-control" id="txt_ubicacion" name="txt_ubicacion" value="{{old('txt_ubicacion')}}">
            </div>
            <hr>
            <div class="form-group">
                (*) Campos Obligatorios
            </div>  
            <button type="submit" class="btn btn-primary">Registrar</button>
            <a href="{{url('distrito')}}" class="btn btn-primary">Volver</a>
        </form>  
    </div>
    @include('layout.script_pie')
</body>
</html>

resources/views/cliente/listado.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestionar Clientes</title>
</head>
<body>
    
    <h2>Lista de Clientes</h2>
    <a href="{{url('Cliente/create')}}">Nuevo Cliente</a>
    <table>
        <thead>
            <tr>
                <td>Nombre</td>
                <td>Apellido</td>
                <td>DNI</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Armando</td>
                <td>Mantilla</td>
                <td>77702329</td>
            </tr>
        </tbody>
    </table>
</body>
</html>

resources/views/cliente/nuevo.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nuevo Cliente</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h2>Nuevo Cliente</h2>
        <hr>
        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">Nombres</label>
                <input type="text" class="form-control" id="txt_nombres" name="txt_nombres" required>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Apellidos</label>
                <input type="text" class="form-control" id="txt_apellidos" name="txt_apellidos" required>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">DNI</label>
                <input type="text" class="form-control" id="txt_dni" name="txt_dni" required>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Telefono</label>
                <input type="text" class="form-control" id="txt_telefono" name="txt_telefono">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Correo Electronico</label>
                <input type="email" class="form-control" id="txt_email" name="txt_email">
            </div>
            <button type="submit" class="btn btn-primary">Registrar</button>
        </form>  
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

resources/views/layout/script_cabecera.blade.php
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

resources/views/layout/script_pie.blade.php
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!--Referencia Iconos-->
<script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" data-auto-replace-svg="nest"></script>